In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

#Load the cleaned dataset
ds = pd.read_csv("new_cleaned.csv")
ds

,Unnamed: 0,name,company,year,Price,kms_driven,fuel_type
0,0,Santro Xing XO eRLX Euro III,Hyundai,2007,80000.0,45000,Petrol
1,3,Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000.0,28000,Petrol
2,4,EcoSport Titanium 1.5L TDCi,Ford,2014,575000.0,36000,Diesel
3,6,Figo,Ford,2012,175000.0,41000,Diesel
4,7,Eon,Hyundai,2013,190000.0,25000,Petrol
...,...,...,...,...,...,...,...
646,883,Suzuki Ritz VXI ABS,Maruti,2011,270000.0,50000,Petrol
647,885,Indica V2 DLE BS III,Tata,2009,110000.0,30000,Diesel
648,886,Corolla Altis,Toyota,2009,300000.0,132000,Petrol
649,888,Zest XM Diesel,Tata,2018,260000.0,27000,Diesel
650,889,Quanto C8,Mahindra,2013,390000.0,40000,Diesel

In [4]:
# removing unnamed column
df=df.loc[:, ~df.columns.str.contains('^Unnamed')]                
df

NameError: name 'df' is not defined